questions = [
    {'Number': '1',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '2',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '3',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '4',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '5',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '6',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '7',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '8',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '9',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '10',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '11',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '12',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '13',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '14',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '15',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '16',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '17',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '18',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '19',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '20',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '21',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '22',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '23',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '24',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     },
    {'Number': '25',
     'Statement': 'the question',
     'Choices': [('a', 'words'),
                 ('b', 'words'),
                 ('c', 'words'),
                 ('d', 'words')]
     }
]
