questions = [
    {'Number': '1',
     'Statement': 'The ___________, which extends from the rear of the brainstem, coordinates voluntary movements and enables nonverbal learning and memory.',
     'Choices': [('a', 'amygdala'),
                 ('b', 'hypothalamus'),
                 ('c', 'cerebellum'),
                 ('d', 'hippocampus')]
     },
    {'Number': '2',
     'Statement': 'There are many states of consciousness, in addition to normal waking awareness. They usually occur spontaneously, are ___________, or _____________.',
     'Choices': [('a', 'unconsciously induced, deliberately induced'),
                 ('b', 'physiologically induced, psychologically induced'),
                 ('c', 'randomly generated, systematically elicited'),
                 ('d', 'environmentally stimulated, occur naturally')]
     },
    {'Number': '3',
     'Statement': 'The most effective clinical application that hypnosis is primarily used for is in___________.',
     'Choices': [('a', 'healing/pain control'),
                 ('b', 'retrieving forgotten memories'),
                 ('c', 'behavior modification'),
                 ('d', 'criminal reformation')]
     },
    {'Number': '4',
     'Statement': "Piaget’s Stages of Cognitive Development include the _____________ stage, where children begin to represent things with words and images.",
     'Choices': [('a', 'Sensorimotor'),
                 ('b', 'Preoperational'),
                 ('c', 'Concrete Operational'),
                 ('d', 'Formal Operational')]
     },
    {'Number': '5',
     'Statement': """In Erikson’s Stages of Psychosocial Development, the critical issue or “crisis” of young adulthood is ________________, the struggle to form close relationships and gain the capacity for intimate love.""",
     'Choices': [('a', 'initiative vs. guilt'),
                 ('b', 'competence vs. inferiority'),
                 ('c', 'integrity vs. despair'),
                 ('d', 'intimacy vs. isolation')]
     },
    {'Number': '6',
     'Statement': 'Certain foods that are described as having an acquired taste (like blood sausage) are good examples of ____________________.',
     'Choices': [('a', 'perception'),
                 ('b', 'top-down processing'),
                 ('c', 'sensation'),
                 ('d', 'bottom-up processing')]
     },
    {'Number': '7',
     'Statement': 'Which of the following are NOT grouping principles identified by Gestalt Psychologists?',
     'Choices': [('a', 'Proximity'),
                 ('b', 'Closure'),
                 ('c', 'Continuity'),
                 ('d', 'none of these')]
     },
    {'Number': '8',
     'Statement': "According to Pavlov’s theory of classical conditioning, a(n) _____________ which elicits a natural, unconditioned response is paired with a(n) ______________, which after multiple pairings becomes the conditioned stimulus.",
     'Choices': [('a', 'unconditioned stimulus; neutral stimulus'),
                 ('b', 'neutral stimulus; unconditioned stimulus'),
                 ('c', 'conditioned response; unconditional stimulus'),
                 ('d', 'none of these')]
     },
    {'Number': '9',
     'Statement': 'Getting up to turn off an alarm clock is an example of ______________ in operant conditioning.',
     'Choices': [('a', 'positive reinforcement'),
                 ('b', 'negative reinforcement'),
                 ('c', 'positive punishment'),
                 ('d', 'negative punishment')]
     },
    {'Number': '10',
     'Statement': 'According to George Miller, short term memory has a capacity of roughly ___________ (±2) information bits.',
     'Choices': [('a', '4'),
                 ('b', '7'),
                 ('c', '9'),
                 ('d', '12')]
     },
    {'Number': '11',
     'Statement': 'Telling a person that there is a 1 in 100 chance they will win the top prize in a raffle instead of telling them there is a 99 in 100 chance that they won’t is an example of ______________.',
     'Choices': [('a', 'framing'),
                 ('b', 'intuition'),
                 ('c', 'heuristic reasoning'),
                 ('d', 'cognition')]
     },
    {'Number': '12',
     'Statement': 'Searching for information that supports preconceptions and ignoring or distorting contrary information is the definition of_____________.',
     'Choices': [('a', 'mental set'),
                 ('b', 'availability heuristic'),
                 ('c', 'preconception set'),
                 ('d', 'none of these')]
     },
    {'Number': '13',
     'Statement': 'Intelligence is defined as the ability to _________.',
     'Choices': [('a', 'learn from experience'),
                 ('b', 'solve problems'),
                 ('c', 'use knowledge to adapt to new situations'),
                 ('d', 'all of these')]
     },
    {'Number': '14',
     'Statement': "Which of the following is NOT one of Howard Gardner’s theory of multiple intelligences?",
     'Choices': [('a', 'intrapersonal intelligence'),
                 ('b', 'interpersonal intelligence'),
                 ('c', 'musical intelligence'),
                 ('d', 'creative intelligence')]
     },
    {'Number': '15',
     'Statement': 'Industrial/Organizational Psychology is made up of ____________ psychology, which applies psychological principles to selecting and evaluating workers; _____________ psychology, which considers things like the influence of work environment and management style on employee motivation and satisfaction; and ____________ psychology, which studies human abilities and adapting technology to suit those human abilities.',
     'Choices': [('a', 'Organizational, Personnel, Human Factors'),
                 ('b', 'Human Factors, Organizational, Personnel'),
                 ('c', 'Personnel, Organizational, Human Factors'),
                 ('d', 'none of these')]
     },
    {'Number': '16',
     'Statement': 'Leon Festinger proposed in his theory of ___________ in 1957 that we act to reduce discomfort when two of our thoughts are inconsistent.',
     'Choices': [('a', 'cognitive dissonance'),
                 ('b', 'self persuasion'),
                 ('c', 'foot in the door'),
                 ('d', 'social facilitation')]
     },
    {'Number': '17',
     'Statement': "Janica has heard a song on the radio many times in the last few weeks. She didn’t really like it at first, but now it is starting to grow on her. What social psychological principle does this represent?",
     'Choices': [('a', 'altruism'),
                 ('b', 'the mere exposure effect'),
                 ('c', 'cognitive dissonance'),
                 ('d', 'central route of persuasion')]
     },
    {'Number': '18',
     'Statement': "In Freud’s Psychodynamic theory, the _____ represents the drive to satisfy the pleasure principle.",
     'Choices': [('a', 'superego'),
                 ('b', 'id'),
                 ('c', 'ego'),
                 ('d', 'repression')]
     },
    {'Number': '19',
     'Statement': "Tests like the Rorshach inkblot are called ________ tests, because they use ambiguous stimuli to assess the subject’s inner dynamics.",
     'Choices': [('a', 'projective'),
                 ('b', 'introspective'),
                 ('c', 'psychodynamic'),
                 ('d', 'illustrative')]
     },
    {'Number': '20',
     'Statement': 'The tendency that most people have to see themselves as better than average is called the _____________.',
     'Choices': [('a', 'self-serving bias'),
                 ('b', 'fundamental attribution error'),
                 ('c', 'social comparison effect'),
                 ('d', 'none of these')]
     },
    {'Number': '21',
     'Statement': 'In order for a behavior to be classified as a psychological disorder, it must be ______________.',
     'Choices': [('a', 'dysfunctional'),
                 ('b', 'deviant'),
                 ('c', 'distressful'),
                 ('d', 'all of these')]
     },
    {'Number': '22',
     'Statement': '_________ is sometimes called the sexist psychological disorder because it affects nearly twice as many women as men worldwide.',
     'Choices': [('a', 'major depression'),
                 ('b', 'general anxiety'),
                 ('c', 'paranoid schizophrenia'),
                 ('d', 'multi-phobic personality disorder')]
     },
    {'Number': '23',
     'Statement': """The literal translation of schizophrenia means “split mind” which refers to______________.""",
     'Choices': [('a', 'a multiple personality split'),
                 ('b', 'a moral split where individuals feel separated from their surrounding culture'),
                 ('c', 'a split from reality manifested through disorganized thinking'),
                 ('d', 'none of these')]
     },
    {'Number': '24',
     'Statement': 'The main goal of psychoanalysis is to _______________________.',
     'Choices': [('a', 'promote positive self-regard'),
                 ('b', 'give insight into origins of disorders to resolve growth impeding inner conflicts'),
                 ('c', 'document specific behaviors for clients to interpret and control'),
                 ('d', 'all of these')]
     },
    {'Number': '25',
     'Statement': 'The drug Prozac partially blocks the normal reuptake of serotonin which has the following effect:',
     'Choices': [('a', 'the enhanced mood from the excess of serotonin is cut short'),
                 ('b', 'the enhanced mood from the excess of serotonin is extended'),
                 ('c', 'the depressed mood from a shortage of serotonin is cut short'),
                 ('d', 'the depressed mood from a shortage of serotonin is extended')]
     }
]
